### PR TITLE
Assignment: Test the Video Model

### PR DESCRIPTION
**Pull request by twoller**

### CODE REVIEW

**Comment by twoller** [comment]
@tomtomecek  I used `should validate_presence_of` shoulda-matchers only for this because I was reading through the thoughtbot/shoulda-matchers and they consider `validate_uniqueness_of` an ActiveRecord matcher. I also deleted the `category_spec.rb` so I can stay in step with the assignments. I'll use the appropriate matchers when I test for the associations

**Comment by tomtomecek** [comment]
Its ok to use shoulda matchers, because they validate only whether you have written the validation method there or not.

**Comment by twoller** [comment]
OK, Thanks. Is this good to merge?

I'll add more matchers when I get the `category_spec.rb` set up.

**Comment by tomtomecek** [comment]
Looks fine!

**Pull request merged**
